### ISSUE TITLE
Should not take care of array indentation

### ISSUE THREAD

**Issue by kri5** [GoogleCloudPlatform/cassandra-cloud-backup#11]
There is a case not working, but that is valid yaml.

```
data_file_directories:
  - "/var/lib/cassandra/data"
```
is a working case, but
```
data_file_directories:
- "/var/lib/cassandra/data"
```
is not, but this is valid yaml, and for example it is the way ruby output yaml.

I tried to find a fix, but i'm really not familiar with awk...

Any ideas?

**Comment by kinghrothgar** [comment]
My understanding of YAML is that is not valid.  From the YAML documentation: "In general, a node must be indented further than its parent node. All sibling nodes must use the exact same indentation level, however the content of each sibling node may be further indented independently."  http://yaml.org/spec/current.html#id2519916

**Comment by sveesible** [comment]
This is an edge case that generally goes against the YAML rule of indentation, the YAML spec 1.2, section 6.1 lists the rule and goes on to cover cases using the - ? : characters as handled by the implementation, but not mandatory part of the spec.  In this case unfortunately the implementation has chosen to stick strictly to the spec.  Ruby, as you mention, has chosen to include these characters as valid indentation.  If you or anyone can modify the awk function to account for these 3 block collection characters, then I will happily consider merging the change. 

> Each node must be indented further than its parent node. All sibling nodes must use the exact  same indentation level. However the content of each sibling node may be further indented independently.
...
 The “-”, “?” and “:” characters used to denote block collection entries are perceived by people 
to be part of the indentation. **This is handled on a case-by-case basis by the relevant 
 productions.**
