### ISSUE TITLE
data_file_directories does not exist

### ISSUE THREAD

**Issue by amitgilad3** [GoogleCloudPlatform/cassandra-cloud-backup#13]
Hi,
when i try to run ./cassandra-cloud-backup.sh -b gs://cassandra-backup/ -vn backup

i get the following error 
data_file_directories does not exist : [/cassandra/data]

i checked the directory and the folder is there 
any ideas?

**Comment by sveesible** [comment]
if that directory is where your data is actually located, then you should check the permissions and make sure that whoever you are running the script has read/write access to that whole directory.
