### ISSUE TITLE
Why using the same USER_OPTIONS variable for cqlsh and nodetool?

### ISSUE THREAD

**Issue by mfouilleul** [GoogleCloudPlatform/cassandra-cloud-backup#20]
Hello,

It is strange to use the same USER_OPTIONS variable for cqlsh and nodetool are they are two different access pattern (one is the database, the other is the JMX), I don't have the same policy for theses two different credentials. 

Can we considerate to split it ?

Max.

**Comment by sveesible** [comment]
do you have a pull request?

**Comment by sveesible** [comment]
no pull request, closing stale issue
