### ISSUE TITLE
Wrong path for directories

### ISSUE THREAD

**Issue by mfouilleul** [GoogleCloudPlatform/cassandra-cloud-backup#21]
Hello,

What is the reason of appending "/data" to ${CASS_HOME} for data_file_directories, commitlog_directory and saved_caches_directory ? It makes impossible to set the ${CASS_HOME} at the Cassandra default value "/var/lib/cassandra". The data_file_directories should be ${CASS_HOME}/data not ${CASS_HOME}/data/data.

https://github.com/GoogleCloudPlatform/cassandra-cloud-backup/blob/master/cassandra-cloud-backup.sh#L282
https://github.com/GoogleCloudPlatform/cassandra-cloud-backup/blob/master/cassandra-cloud-backup.sh#L297
https://github.com/GoogleCloudPlatform/cassandra-cloud-backup/blob/master/cassandra-cloud-backup.sh#L307

Max.

**Comment by mfouilleul** [comment]
I caught this after the following error message:
```
ERROR: Cannot parse data_directories from /etc/cassandra/cassandra.yaml and --home-dir argument  is missing, which should be the $CASSANDRA_HOME path
```

The data_directories is specified in my /etc/cassandra/cassandra.yaml
```
# grep data_file_directories /etc/cassandra/cassandra.yaml -A 1
data_file_directories:
- /var/lib/cassandra/data
```

Is the parse_yaml() working for you?

Max.

**Comment by sveesible** [comment]
https://github.com/GoogleCloudPlatform/cassandra-cloud-backup/commit/c03111ca7031123a32d250640a5b3b2d6797ba76
