### ISSUE TITLE
Saved caches should not be backed up

### ISSUE THREAD

**Issue by kinghrothgar** [GoogleCloudPlatform/cassandra-cloud-backup#3]
As far as I can tell there is no reason to backup saved caches as it is a read cache.  This is just a waste of space.

**Comment by sveesible** [comment]
That's a good point. I think the overall approach I started with was "backup everything someone might want", but in most scenarios that is not really necessary. The case of the commit logs is the same, there are scenarios where someone may want to capture them, but in practice under load you will see the problems you experienced.  I am on the fence about either leaving them in there and require an additional flag to enable them, or just yanking them out all together
